export const projectData = [
    {
        title: 'Bibimbox',
        date: '2023 - 24',
        imgUrl: '/bibimbox/LogoMockup.png',
        type: 'design',
        shortcut: '/bibimbox',
        desc: 'Bibimbox is a Korean fast casual spot, serving up fast, fresh, and delicious meals reminiscent of Korean street food and home-cooked meals. Inspired by the Korean word "bibimbap", Bibimbox focuses on quick service and yummy food, specializing in customizable bibimbap bowls and crispy Korean fried chicken. The bright colors and simple doodles that make up its branding are meant to exude a friendly, casual, and fun atmosphere.',
        role: ['BRANDING', 'GRAPHIC DESIGN', 'WEBSITE DESIGN'],
        tools: ['ADOBE PHOTOSHOP', 'ADOBE ILLUSTRATOR', 'ADOBE INDESIGN', 'FIGMA'],
        languages: ['HTML/CSS'],
        link: 'https://eatbibimbox.com',
        feature: true,
    },
    {
        title: 'InSync',
        date: '2022 - 23',
        imgUrl: '/insync/InsyncFeature.png',
        type: 'code',
        shortcut: '/insync',
        desc: 'InSync is a web-based application where users can match with each other based on their music compatibility. We drew UI inspiration from Spotify, and utilized Spotify\'s API to calculate compatibility scores based on your recent listening history. We used React to develop our front-end, and Firebase to store our user data.\nInspired by the multitudes of Spotify and dating apps out there, and our personal love for music and connection.',
        role: ['FRONT-END DEVELOPER', 'UI/UX DESIGNER'],
        tools: ['FIGMA', 'TRELLO', 'VS CODE', 'GITHUB'],
        languages: ['JAVASCRIPT', 'REACT', 'HTML/CSS'],
        overview: 'InSync was created out of necessity — namely, my friends and I\'s senior project. However, the birth of its concept came from a place of love and connection, and what brought us close in the first place: music. Much of our initial friendship was centered around both alike and dissimilar music tastes — sharing music through Spotify links, roasting music through Spotify blends. It was from this shared experience that the idea for InSync came to be. What if we could facilitate that connection? Thus, InSync. The various viral Spotify apps that already exist helped, too. Starting from a research proposal and going through several presentations with our faculty advisor, multiple blockers with the development of the product, and about three different iterations of our matching algorithm, InSync eventually came to be. Created with love, late nights, and lots of stupid jokes by Nancy Chen, Christopher In, Nicole Liang, and Arthur Liu.',
        development: 'The development process for InSync was fairly straightforward, give or take a few curveballs. We started with a research proposal, which consisted of citations from peer-reviewed articles backing the existence of connection through music. We each took time to learn to use the Spotify API/SDK to integrate Spotify\'s music and listening data into our app. Initially meant to be a mobile app, we discovered Spotify has different APIs for Android and Apple, so we pivoted to a web-based app. We used Figma to plan our UI/UX designs and user flows, and React to develop the frontend. We used Firebase and JavaScript for data storage, manipulation, and logic. Finally, we used Trello and GitHub for project management and code control, respectively.',
        feature: true,
    },
    {
        title: 's2udy',
        date: '2021',
        imgUrl: '/s2udy.png',
        type: 'code',
        shortcut: '/s2udy',
        desc: 's2udy is a collaborative studying app developed in the thick of lockdown during the COVID-19 pandemic. Developed for Android devices in Android Studio, the main language used was Java, with some light HTML for the project documentation’s formatting. The back-end was supported with Parse Platform, with data storage supported by Parse and MongoDB. Born from the realization that community and connection are crucial to living a good life (at least for me!).',
        role: ['PRODUCT DESIGNER', 'UI/UX DESIGNER', 'FULL-STACK DEVELOPER'],
        tools: ['ANDROID STUDIO', 'MONGODB', 'GITHUB', 'TRELLO', 'FIGMA'],
        languages: ['JAVA', 'HTML'],
        overview: 'The peak of COVID-19’s quarantine came with the realization that community and connection were critical aspects of life that I had often taken for granted. Video calls replaced study sessions and co-op games replaced hangouts (shoutout Among Us); technology became many people’s main channel for connecting with their community. With this in mind, the idea for s2udy slowly started to form. Every component of s2udy — the chat, task-list, timer, music player — was something my friends and I had used to some extent while studying before, whether in person or remotely. However, there wasn’t something (that I knew of, at least) that neatly packaged all those features into one product, so that’s what I sought out to do. Although never published to the app store, s2udy was my first project where I was able to lead every aspect of it, from idea conception to architecture design to the actual meat of the code – it’ll always be something I feel a little bit proud of.',
        development: 'The development of s2udy lasted all of four weeks, from start to finish. Much of the project timeline was mapped out on Trello before development started, giving me clear milestones to hit by the end of each week to ensure I could finish within the given timeframe. The data models for User and Room objects were designed by me and supported by Parse Platforms/MongoDB. The user authentication, information storage, and messaging storage were also supported by Parse Platforms. All code was written in Android Studio using Java, and the front-end was designed and coded with Figma and Java, as well as multiple Android frontend libraries. Like always, Trello and GitHub were used for project and code management, respectively.',
        link: "https://github.com/nicolenliang/s2udy",
        feature: true,
    },
    {
        title: 'Asian American Student Union',
        date: '2020 - 23',
        imgUrl: '/aasu/misc2.png',
        type: 'design',
        shortcut: '/aasu',
        desc: 'The Asian American Student Union at the University of Florida was founded in 1993 and is comprised of 17 organizations, all aiming to foster Asian and Asian-American culture, unity, and awareness across campus through cultural events, meetings, and workshops. As Multimedia Director for one sub-org, one affiliate org, and the Union as a whole, I helped create graphics, flyers, and merchandise, as well as curate social media presences to help promote each organization.',
        feature: true,
    },
    {
        title: 'Type & Branding',
        date: '2020 - 23',
        imgUrl: '/wip.png',
        type: 'design',
        shortcut: '/type_branding',
        desc: 'This page is still a work in progress. Check back later for more information! :)',
    },
    {
        title: 'Film Photography',
        date: '2019 - now',
        imgUrl: '/w_camera.jpg',
        type: 'design',
        shortcut: '/film_photography',
        desc: 'After I finally figured out how disposable cameras work in 2019, film has been a favorite medium of mine to capture moments and feelings in time. Whether it be a beautiful view or a sweet moment with friends, film photography adds a layer of permanence and intentionality to each shot that enhances it that much more. Aside from film, I also dabble in digital photography/editing, with a Sony A3600 and Adobe Lightroom. Film is typically shot with a Canon AE-1, occasionally with a $15 disposable from Walgreens.',
        feature: true,
    },
    {
        title: 'Illustration',
        date: '2017 - now',
        imgUrl: '/illustration/18.jpg',
        type: 'design',
        shortcut: '/illustration',
        desc: 'Since I discovered that you could make something out of nothing with just a #2 pencil and a sheet of copy paper, I\'ve loved drawing and illustration. It\'s been an intrinsic part of my life for as long as I can remember, and is still something I try to maintain in my life, whether through creating illustrations as gifts or just drawing for personal fulfillment. This page features a compilation of my works, old and new, that I feel a bit prouder of.',
        feature: true,
    },
];
