export const workData = [
    {
        id: 1,
        title: 'InSync',
        date: '2022 - 23',
        imgUrl: '/temp1.jpg',
        type: 'code',
        shortcut: '/insync',
    },
    {
        id: 2,
        title: 'Facebook Marketplace - Live Shopping',
        date: '2022',
        imgUrl: '/temp6.jpg',
        type: 'code',
        shortcut: '/fbm_liveshopping',
    },
    {
        id: 3,
        title: 's2udy',
        date: '2021',
        imgUrl: '/temp2.jpg',
        type: 'code',
        shortcut: '/s2udy',
    },
    {
        id: 4,
        title: 'Instagram Clone',
        date: '2021',
        imgUrl: '/temp5.jpg',
        type: 'code',
        shortcut: 'insta_clone',
    },
    {
        id: 5,
        title: 'Twitter Clone',
        date: '2021',
        imgUrl: '/temp4.jpg',
        type: 'code',
        shortcut: '/twitter_clone',
    },
    {
        id: 6,
        title: 'Rotten Tomatoes Clone',
        date: '2021',
        imgUrl: '/temp5.jpg',
        type: 'code',
        shortcut: '/rotten_tomatoes_clone',
    },
    {
        id: 7,
        title: 'UI/UX Design',
        date: '2020 - 23',
        imgUrl: '/temp1.jpg',
        type: 'design',
        shortcut: '/uiux_design',
    },
    {
        id: 8,
        title: 'Type & Branding',
        date: '2020 - 23',
        imgUrl: '/temp2.jpg',
        type: 'design',
        shortcut: '/type_branding',
    },
    {
        id: 9,
        title: 'Film Photography',
        date: '2022 - now',
        imgUrl: '/film/Amy :: 2023.jpg',
        type: 'design',
        shortcut: '/film_photography',
    },
    {
        id: 10,
        title: 'Asian American Student Union',
        date: '2021 - 23',
        imgUrl: '/temp4.jpg',
        type: 'design',
        shortcut: '/aasu',
    },
    {
        id: 11,
        title: 'Society of Asian Scientists and Engineers',
        date: '2021 - 22',
        imgUrl: '/temp3.jpg',
        type: 'design',
        shortcut: '/sase',
    },
    {
        id: 12,
        title: 'Chinese American Student Association',
        date: '2020 - 21',
        imgUrl: '/temp6.jpg',
        type: 'design',
        shortcut: '/casa',
    },
    {
        id: 13,
        title: 'University of Florida',
        date: '2022 - 23',
        imgUrl: '/temp7.jpg',
        type: 'design',
        shortcut: '/uf_design'
    },
    {
        id: 14,
        title: 'Illustration',
        date: '2017 - now',
        imgUrl: '/temp8.jpg',
        type: 'design',
        shortcut: '/illustration',
    },
];
