export const workData = [
    {
        id: 1,
        title: 'InSync',
        date: '2022 - 23',
        imgUrl: '/insync.jpg',
        type: 'code',
        shortcut: '/insync',
        desc: 'InSync is a web-based application where users can match with each other based on their music compatibility. We drew UI inspiration from Spotify, and utilized Spotify\'s API to calculate compatability scores based on your recent listening history. We used React to develop our front-end, and Firebase to store our user data.\nInspired by the multitudes of Spotify and dating apps out there, and our personal love for music and connection.',
        role: ['FRONT-END DEVELOPER', 'UI/UX DESIGNER'],
        tools: ['FIGMA', 'TRELLO', 'VS CODE', 'GITHUB'],
        languages: ['JAVASCRIPT', 'REACT', 'HTML/CSS'],
        overview: 'InSync was created out of necessity -- namely, my friends and I\'s senior project. However, the birth of its concept came from a place of love and connection, and what brought us close in the first place: music. Much of our initial friendship was centered around both alike and dissimilar music tastes -- sharing music through Spotify links, roasting music through Spotify blends. It was from this shared experience that the idea for InSync came to be. What if we could facilitate that connection? Thus, InSync. The various viral Spotify apps that already exist helped, too. Starting from a research proposal and going through several presentations with our faculty advisor, multiple blockers with the development of the product, and about three different iterations of our matching algorithm, InSync eventually came to be. Created with love, late nights, and lots of stupid jokes by Nancy Chen, Christopher In, Nicole Liang, and Arthur Liu.',
        development: 'The development process for InSync was fairly straightforward, give or take a few curveballs. We started with a research proposal, which consisted of citations from peer-reviewed articles backing the existence of connection through music. We each took time to learn to use the Spotify API/SDK to integrate Spotify\'s music and listening data into our app. Initially meant to be a mobile app, we discovered Spotify has different APIs for Android and Apple, so we pivoted to a web-based app. We used Figma to plan our UI/UX designs and user flows, and React to develop the frontend. We used Firebase and JavaScript for data storage, manipulation, and logic. Finally, we used Trello and GitHub for project management and code control, respectively.',
        feature: true,
    },
    {
        id: 2,
        title: 'Facebook Marketplace - Live Shopping',
        date: '2022',
        imgUrl: '/temp6.jpg',
        type: 'code',
        shortcut: '/fbm_liveshopping',
        desc: 'This page is still a work in progress. Check back later for more information! :)',
    },
    {
        id: 3,
        title: 's2udy',
        date: '2021',
        imgUrl: '/temp2.jpg',
        type: 'code',
        shortcut: '/s2udy',
        desc: 'This page is still a work in progress. Check back later for more information! :)',
        feature: true,
    },
    {
        id: 4,
        title: 'Instagram Clone',
        date: '2021',
        imgUrl: '/temp5.jpg',
        type: 'code',
        shortcut: 'insta_clone',
        desc: 'This page is still a work in progress. Check back later for more information! :)',
    },
    {
        id: 5,
        title: 'Twitter Clone',
        date: '2021',
        imgUrl: '/temp4.jpg',
        type: 'code',
        shortcut: '/twitter_clone',
        desc: 'This page is still a work in progress. Check back later for more information! :)',
    },
    {
        id: 6,
        title: 'Rotten Tomatoes Clone',
        date: '2021',
        imgUrl: '/temp5.jpg',
        type: 'code',
        shortcut: '/rotten_tomatoes_clone',
        desc: 'This page is still a work in progress. Check back later for more information! :)',
    },
    {
        id: 7,
        title: 'UI/UX Design',
        date: '2020 - 23',
        imgUrl: '/temp1.jpg',
        type: 'design',
        shortcut: '/uiux_design',
        desc: 'This page is still a work in progress. Check back later for more information! :)',
        feature: true,
    },
    {
        id: 8,
        title: 'Type & Branding',
        date: '2020 - 23',
        imgUrl: '/temp2.jpg',
        type: 'design',
        shortcut: '/type_branding',
        desc: 'This page is still a work in progress. Check back later for more information! :)',
    },
    {
        id: 9,
        title: 'Film Photography',
        date: '2019 - now',
        imgUrl: '/film/30.jpg',
        type: 'design',
        shortcut: '/film_photography',
        desc: 'Sparked in 2019 after I finally figured out how disposable cameras work, film has been a favorite medium of mine to capture singular moments in time. Whether it be a beautiful view or a sweet moment with friends, film photography adds a layer of nostalgia that exactly enhances the feeling of an occasion. Typically shot on Canon AE-1, occasionally with a $15 disposable from Walgreens.',
        feature: true,
    },
    {
        id: 10,
        title: 'Asian American Student Union',
        date: '2021 - 23',
        imgUrl: '/aasu/merch1.png',
        type: 'design',
        shortcut: '/aasu',
        desc: 'The Asian American Student Union at the University of Florida was founded in 1993 to foster Asian and Asian-American culture, unity, and awareness across campus. Comprised of 5 sub-organizations, 3 programs, and 9 affiliate organizations, AASU hosts a multitude of cultural events, meetings, and workshops to promote Asian-American culture on campus. As Multimedia Director, I was tasked with creating graphics, flyers, and merchandise, as well as curating our social media presence to help promote the organization.',
        feature: true,
    },
    {
        id: 11,
        title: 'Society of Asian Scientists and Engineers',
        date: '2021 - 22',
        imgUrl: '/temp3.jpg',
        type: 'design',
        shortcut: '/sase',
        desc: 'This page is still a work in progress. Check back later for more information! :)',
    },
    {
        id: 12,
        title: 'Chinese American Student Association',
        date: '2020 - 21',
        imgUrl: '/temp6.jpg',
        type: 'design',
        shortcut: '/casa',
        desc: 'This page is still a work in progress. Check back later for more information! :)',
    },
    {
        id: 13,
        title: 'University of Florida',
        date: '2022 - 23',
        imgUrl: '/temp7.jpg',
        type: 'design',
        shortcut: '/uf_design',
        desc: 'This page is still a work in progress. Check back later for more information! :)',
    },
    {
        id: 14,
        title: 'Illustration',
        date: '2017 - now',
        imgUrl: '/illustration/18.jpg',
        type: 'design',
        shortcut: '/illustration',
        desc: 'Since I discovered that you could create with just a #2 pencil and a sheet of copy paper, I\'ve loved drawing and illustration. It\'s been an intrinsic part of my life for as long as I can remember, and still something I try to keep up with in my free time. This page features a compilation of some of the works I\'m prouder of.',
        feature: true,
    },
];
